global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "kafka-loadtest"
    static_configs:
      - targets:
          - "producer:8000" # prod
          - "consumer:8001"